### PR TITLE
[2.0] refactored travis config to execute php 7.1 tests with simple-phpunit

### PR DESCRIPTION
**Pull request by sebastianblum**
| Q | A
| --- | ---
| Branch? | 2.0
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes/no
| License | MIT

Another try to fix the unit tests.
I need this pull request to run the travis tests.

### CODE REVIEW

**Comment by dbu** [comment]
squashed and merged. thanks a lot!

re the "nightly" fail: we could maybe remove the php-cs-fixer from require-dev. if i read .travis.yml, it seems not to be used. and we have styleci which does the same as the cs fixer. i'll try that.

**Comment by sebastianblum** [comment]
Thank you @dbu
Can you now please have a Look at #1025

**Comment by sebastianblum** [comment]
I will look at the nightly build later, I saw a lot failing builds because of cs-fixer

**Comment by dbu** [comment]
i already fixed the nightly build in #1031

**Pull request merged**
