### PR TITLE
Update Configuration.php

### PR DESCRIPTION
**Pull request by nilov**
Fixed an exception if there is not defined "png_compression_level".

### CODE REVIEW

**Comment by makasim** [comment]
What kind of exception you get? What config look like when you get it?

**Comment by nilov** [comment]
This is exception:

request.CRITICAL: Uncaught PHP Exception Imagine\Exception\InvalidArgumentException: "png_compression_level option should be an integer from 0 to 9" at vendor\imagine\imagine\lib\Imagine\Gd\Image.php line 559 {"exception":"[object] (Imagine\\Exception\\InvalidArgumentException(code: 0): png_compression_level option should be an integer from 0 to 9 at vendor\\imagine\\imagine\\lib\\Imagine\\Gd\\Image.php:559)"} []

This is config:

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        image_big:
            quality: 900
            filters:
                thumbnail: { size: [500, 500], mode: outbound }

**Comment by makasim** [comment]
Could you provide a stack trace too. I am trying to figure out how you were able to get. I've never seen this exception, even with the config like you posted.

**Comment by nilov** [comment]
This is image - 
bb0e9492f06a542debeb4a1ad7b58e09_large

Try with it

**Comment by makasim** [comment]
I asked for a stack trace.

**Comment by makasim** [comment]
Feel free to reopen if there is something left.

**Pull request closed without merging**
