### PR TITLE
Solve issues with file type, which wasn’t converted to the new standard

### PR DESCRIPTION
**Pull request by jorisros**
| Q | A
| --- | ---
| Branch? | 2.0 
| Bug fix? | yes/
| New feature? | no
| BC breaks? | no <only sf3 tested>
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | #943
| License | MIT
| Doc PR |

### CODE REVIEW

**Comment by jorisros** [comment]
Thank you, i have created a issue for this. #976

**Comment by cedricziel** [comment]
Thx @jorisros !

**Comment by trsteel88** [comment]
According to composer.json php5.3 is supported. The class constant is only available from php5.5.

**Comment by cedricziel** [comment]
The PR was made against the 2.0 branch, of the Bundle, which requires PHP 7. :)

Ref: https://github.com/liip/LiipImagineBundle/blob/2.0/composer.json#L21

**Comment by robfrawley** [comment]
We actually discussed matching the Symfony 4.x requirement and having PHP 7.1 be the minimum requirement for 2.x, but I guess we forgot to make that change. Someone should submit a PR handling that...

**Pull request merged**
