### PR TITLE
Allow to configure the HTTP response code for redirects

### PR DESCRIPTION
**Pull request by lstrojny**
| Q | A
| --- | ---
| Branch? | 1.0
| Bug fix? | yes
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | #969
| License | MIT

Makes redirect code configurable.

### CODE REVIEW

**Comment by lstrojny** [comment]
Adding support for 3.2

**Comment by lstrojny** [comment]
Hopefully fixed all compatibility issues now. Ready to be merged from my side

**Comment by robfrawley** [comment]
Still array syntax issues; please review the CI tests.

**Comment by lstrojny** [comment]
@robfrawley thanks for pinging, will check

**Comment by lstrojny** [comment]
We are good now

**Pull request merged**
