### PR TITLE
Update aws_s3.rst to follow the currently mainted library

### PR DESCRIPTION
**Pull request by appeltaert**
- Changed the link to new one
- Changed the config to follow the new factory, and a block below it for the deprecated verison
- Added the mandatory version parameter

### CODE REVIEW

**Comment by dincho** [comment]
I'm getting ```Invalid type for path "liip_imagine.resolvers.images_s3.aws_s3.client_config.XXXXX". Expected scalar, but got array.``` with below config: 

```
liip_imagine:
    cache:      images_s3
    resolvers:
        images_s3:
            aws_s3:
                client_config:
                    credentials: 
                        key: %amazon_s3.key%
                        secret: %amazon_s3.secret%
                    region: %amazon_s3.region%
                    version: %amazon_s3.version%
                bucket:     %amazon_s3.images_cache_bucket%
                proxies:    %amazon_s3.proxies%
```

This is because client_config prototype accepts only scalars, but credentials is array.
AwsS3ResolverFactory should be modified to reflect this configuration.

**Comment by dincho** [comment]
Oh, this is service configuration sorry. Unrelated comment.

**Comment by lsmith77** [comment]
see this comment here https://github.com/liip/LiipImagineBundle/pull/620#issuecomment-151620795

**Comment by makasim** [comment]
fixed in https://github.com/liip/LiipImagineBundle/pull/685. available since 1.4.1

**Pull request closed without merging**
