### PR TITLE
Revert to php-cs-fixer 1.x and run fixer

### PR DESCRIPTION
**Pull request by robfrawley**
| Q | A
| --- | ---
| Branch? | 1.0
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | 
| License | MIT
| Doc PR | 

The move to php-cs-fixer `2.x` was done without migrating the `.styleci.yml` rules. This pull request reverts our `require-dev` dependency back to `1.x`, amends the `.php_cs.dist` file for simplicity, and includes fixes from a `php-cs-fixer` run.

We'll be stuck with this version until the following are fixed:

- https://github.com/Soullivaneuh/styleci-fixers/pull/14
- https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/pull/79
- https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/issues/76

### CODE REVIEW

**Comment by cedricziel** [comment]
We should think about using the phar instead of pulling it in our dependency tree.

**Comment by shakaran** [comment]
@robfrawley it seems that [Style CI has given up with upgrade to 2.x php-cs-fixer](https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/issues/76#issuecomment-325372083), so probably it is better rewrite the .php_cs file instead and use new version and forget about .styleci.yml

**Comment by robfrawley** [comment]
@shakaran Yes, I know the state of Style CI integration with php-cs-fixer is stalled. This was simply a quick fix; a more long-term solution needs to be implemented, for sure.

**Comment by shakaran** [comment]
@robfrawley would you accept a PR where I implement the exact same filters/fixers, etc in the .php_cs file? So php-cs-fixer 2.x version could be used again?

**Comment by robfrawley** [comment]
Sure would.

**Comment by shakaran** [comment]
@robfrawley Done PR #992

**Pull request merged**
