### PR TITLE
lets just run simple-phpunit

### PR DESCRIPTION
**Pull request by dbu**
| Q | A
| --- | ---
| Branch? | 2.0
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | => travis
| Fixed tickets | -
| License | MIT
| Doc PR | -

Trying to fix setup of travis testing.

### CODE REVIEW

**Comment by sebastianblum** [comment]
@dbu David, in der composer.json ist das bin Dir mit bin anstatt vendor/bin angegeben.
Du müsstest die Tests ohne ./vendor/ laufen lassen oder die composer.json anpassen.

**Comment by dbu** [comment]
> in der composer.json ist das bin-dir mit "bin" anstatt "vendor/bin" angegeben.
> Du müsstest die Tests ohne ./vendor/ laufen lassen oder die composer.json anpassen.

nur für branch 1.0, dieser merge request ist für 2.0 und da wurde die bin config entfernt. würde das phpunit binary nicht gefunden, müsste auch ein fehler ausgegeben werden.

**Comment by dbu** [comment]
@lsmith77 would you have an idea why this is not running any tests? locally it worked for me.

**Comment by lsmith77** [comment]
seem to be passing now .. ?

**Comment by cedricziel** [comment]
Passing nur IMHO without running any tests. There's no output

**Comment by lsmith77** [comment]
ah .. strange

**Comment by sebastianblum** [comment]
@dbu & @lsmith77 the problem is in my opinion, that symfony/phpunit-bridge runs phpunit 5.7 at php 7.1  (there are no tests executed) and phpunit 6.5 at 7.2 (tests are fine)

I'm trying a lot in this pull request https://github.com/liip/LiipImagineBundle/pull/1029 but locally it is running because of phpunit ^6.0 in the composer.json

**Comment by dbu** [comment]
if we can move everything to phpunit 6 only, thats fine too. we don't need to support different versions of phpunit or anything, the tests are just for this bundle itself. does #1029 replace this PR?

**Comment by sebastianblum** [comment]
no @dbu #1029 has too much changes and should be deleted. 
If I have a solution, you can update this request or I will create a new clean pull request.

**Comment by sebastianblum** [comment]
@dbu can you please have a look at https://travis-ci.org/liip/LiipImagineBundle/builds/324187910
now #1029 looks much better

**Comment by dbu** [comment]
that looks indeed a lot better. i would be happy if we just merge #1029, no need to further split that up imho.

**Comment by sebastianblum** [comment]
@dbu can you squash #1029 ?

**Comment by dbu** [comment]
fixed in #1029

**Pull request closed without merging**
