### PR TITLE
Switched the documentation from Markdown to ReStructuredText

### PR DESCRIPTION
**Pull request by javiereguiluz**
This change is needed to integrate as soon as possible the LiipImagineBundle documentation on symfony.com, where it'll receive a lot more exposure and, hopefully, will increase the doc contributors.

In addition, some minor tweaks and fixes have been added, including the update of the installation instructions to comply with the [best practices for reusable Symfony bundles](http://symfony.com/doc/current/cookbook/bundles/best_practices.html#installation-instructions).

### CODE REVIEW

**Comment by lsmith77** [comment]
+1 from me

**Comment by makasim** [comment]
>  to integrate as soon as possible the LiipImagineBundle documentation on symfony.com

Just out of curiosity: What bundles could be present on symfony.com and who selects them. is there any rules for that?

+1 of cource

**Comment by javiereguiluz** [comment]
@makasim we'll start with the Top 30 bundles selected by the community (http://symfony.com/blog/the-30-most-useful-symfony-bundles-and-making-them-even-better).

**Comment by makasim** [comment]
@javiereguiluz  thanks.

**Comment by makasim** [comment]
@javiereguiluz is it ready to be merged?

**Comment by javiereguiluz** [comment]
@makasim I think it's ready, but with so many changes, it's possible that some minor syntax error went unnoticed to me. In any case, I'll fix any error that we find once this is merged.

**Comment by lsmith77** [comment]
agreed

**Pull request merged**
