### PR TITLE
Allow Symfony 6.0

### PR DESCRIPTION
**Pull request by franmomu**
| Q | A
| --- | ---
| Branch? | 3.x
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | 
| License | MIT
| Doc | 

I'll take a look later at the errors.

### CODE REVIEW

**Comment by dbu** [comment]
if we do this in version 3 only, it will create quite the pressure to quickly release 3.0 :-)

i wonder how difficult it would be to make it work in the 2.x branch. i might try once you found how to solve the build errors.

**Comment by franmomu** [comment]
This is the easiest way I've found to fix the build, the problem was some service to not be available through the container in tests.

**Comment by dbu** [comment]
> This is the easiest way I've found to fix the build, the problem was some service to not be available through the container in tests.

i like this approach.

now there is a problem with a method signature that got a type declaration in symfony 6.

**Comment by franmomu** [comment]
Closing in favor of https://github.com/liip/LiipImagineBundle/pull/1431

**Pull request closed without merging**
