### PR TITLE
Flysystem v2 support

### PR DESCRIPTION
**Pull request by mynameisbogdan**
| Q | A
| --- | ---
| Branch? | 2.0 
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | #1308 
| License | MIT
| Doc PR | 

Adding support for Flysystem v2 as drop-in replacement in `FlysystemLoaderFactory` and `FlysystemResolverFactory`.

### CODE REVIEW

**Comment by mynameisbogdan** [comment]
@lsmith77 I updated this PR. 

I fixed some mismatches in the tests from the previous PR and put back the check on `ExtensionGuesserInterface` & `MimeTypesInterface` on the loader to maintain BC with Symfony pre-4.3.

**Comment by lsmith77** [comment]
thx .. also thx for removing phpcs dependency.

you re-added support for pre 4.3 versions because you need this yourself?

**Comment by mynameisbogdan** [comment]
No, I tried to maintain BC by keeping the same logic as the loader for v1. But now looking at composer.json, it makes sense to remove it since symfony/mime is mandatory even for symfony v3. 

I pushed an update. 

Thank you.

**Comment by fbourigault** [comment]
Is it possible to not introduce a `flysystem2` configuration value and choose the proper implementation by detecting if V1 or V2 is installed?

**Comment by mynameisbogdan** [comment]
@fbourigault well that's case now. Since the loader and resolver must have an unique service id, I'm handling that in `FlysystemLoaderFactory` (eg `liip_imagine.cache.resolver.prototype.flysystem2` / `liip_imagine.binary.loader.prototype.flysystem2`).

But the configuration value remained the same `flysystem`, so no BC breaks.

**Comment by lsmith77** [comment]
awesome thx.

**Comment by mynameisbogdan** [comment]
Thank you as well.

**Comment by lsmith77** [comment]
ah damn .. hit merge and then I remembered that we have failed to update the UPGRADING.md since a while but would like to get back to doing this .. could you add a new section with config instructions for users upgrading to flysystem2?

**Comment by mynameisbogdan** [comment]
@lsmith77 Well, there are no configuration changes. One can simply run `composer require -W liip/imagine-bundle:2.x-dev league/flysystem:^2.0` and that's it.

Should I make a new PR with this information?

**Comment by lsmith77** [comment]
yes please

**Comment by mynameisbogdan** [comment]
Done in #1359

**Pull request merged**
