### PR TITLE
make configuration compatible with sf3.0

### PR DESCRIPTION
**Pull request by ip512**
As this will break compatibility with sf2.3, is it possible to put this change in a separate branch ? I'm not a version management expert, so if you have better suggestion, feel free to do something else

### CODE REVIEW

**Comment by makasim** [comment]
The current approach does not work in sf3.0, does it?

**Comment by ip512** [comment]
Yes, the setFactoryClass method of Symfony\Component\DependencyInjection\Definition class is marked depracated and will be removed inf sf3.0.
With version 2.6+, there's some deprecated warnings only.

**Comment by makasim** [comment]
so, maybe we can introduce a new imagine_sf30.xml file which is loaded only for sf3.0 version and overwrites services?  wdyt?

In this case it will work for both 2.x and 3.x version at the same time

**Comment by ip512** [comment]
I looked how it's managed in other bundles, in fosuser there is a test in the DI configuration :
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/FOSUserExtension.php#L46-51
I think it's better to avoid config duplication. 
In the meantime, I tried to launch the tests and I realized there's a lot of deprecated warnings and tests failures. Maybe this will require additional work to fix all that.

**Comment by Koc** [comment]
similar to #566

**Comment by lsmith77** [comment]
seems like #566 is indeed a more BC friendly approach

**Pull request closed without merging**
