### PR TITLE
Fixes/Refactor for Symfony 4.3

### PR DESCRIPTION
**Pull request by hjanuschka**
| Q | A
| --- | ---
| Branch? | master
| Bug fix? | no
| New feature? | no
| BC breaks? |  🤔
| Deprecations? | no
| Tests pass? | yes
| License | MIT

hey there 🤚,
we really love this project, and highly depend on it, we are in the process of upgrading all our symfony apps to `4.3` and stumbled upon some issues.

this PR - refactors the bundle and solves following things:

  - remove all deprecation notes
    - Event from Contract
    - EventDispatcher signature
    - MimeType Guesser
    - rootBuilder (i did the initial PR, but somehow missed the tests, https://github.com/liip/LiipImagineBundle/pull/1139)
    - remove `symfony/template` dependency (reference: https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration)

let me know what you think, and if you'd need me to change anything.

### CODE REVIEW

**Comment by franmomu** [comment]
This bundle supports Symfony `"^3.4|^4.0"` versions, so these changes should work in either of those versions. For example, the arguments of the EventDispatcher cannot be swapped, you can use https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/EventDispatcher/LegacyEventDispatcherProxy.php instead.

**Comment by ilyas-gx** [comment]
Hi guys, is there any progress?

**Comment by franmomu** [comment]
I think this is all covered by https://github.com/liip/LiipImagineBundle/pull/1213, https://github.com/liip/LiipImagineBundle/pull/1217, https://github.com/liip/LiipImagineBundle/pull/1218, https://github.com/liip/LiipImagineBundle/pull/1212, https://github.com/liip/LiipImagineBundle/pull/1176 and maybe some more

**Comment by dbu** [comment]
agreed, closing this one.

is there anything left for symfony  4.3 or should we tag a release now?

**Comment by franmomu** [comment]
mmm I haven't seen any deprecation left for symfony 4.3

**Pull request closed without merging**
