### PR TITLE
Fixed wrong rotation for flipped images in auto_rotate filter

### PR DESCRIPTION
**Pull request by Heshyo**
The original code was not rotating (nor flipping) flipped images.

The code has been tested using those images https://github.com/recurser/exif-orientation-examples

### CODE REVIEW

**Comment by lsmith77** [comment]
can you add a test case?

**Comment by Heshyo** [comment]
I was able to setup my test environment but now I'm having issues faking the metadata object.
```php
$metaData = $this->getMock('Metadata\MetadataInterface');

$metaData
	->expects($this->once())
	->method('offsetGet')
	->willReturn("1")
;

$metaData->offsetGet();
// Call to undefined method Mock_MetadataInterface_7f3f507c::offsetGet()
```

Am I missing something obvious? I don't even know where ```MetadataInterface``` is defined (I see in ```ImageInterface``` that ```metadata``` is supposed to return a ```Metadata\MetadataInterface```).

**Comment by lsmith77** [comment]
this interface is part of the "jms/metadata" composer package I guess .. but what makes you believe you need to mock this interface for a test?

**Comment by Heshyo** [comment]
The autorotate needs to get the metadata from the image to know the rotation. So I want to mock it, to avoid having to provide real pictures.

I found the info on https://imagine.readthedocs.org/en/latest/usage/metadata.html. The ```metadata``` function returns a ```Imagine\Image\Metadata\MetadataBag```.

**Comment by Heshyo** [comment]
I added the test cases and followed StyleCI recommendations.

**Comment by lsmith77** [comment]
the style issues were already fixed in master .. it would be best if you start a new branch from current master and cherry pick your changes into there.

**Comment by Heshyo** [comment]
Actually I only fixed the StyleCI issues for the files I modified.
I still created a new PR https://github.com/liip/LiipImagineBundle/pull/654

**Pull request closed without merging**
