### PR TITLE
Allow v0.7 of Imagine Bundle

### PR DESCRIPTION
**Pull request by trsteel88**
https://github.com/avalanche123/Imagine/pull/547

| Q | A
| --- | ---
| Branch? | 1.0 and 2.0
| Bug fix? | yes
| New feature? | no
| BC breaks? | yes
| Deprecations? | no
| Tests pass? | yes
| License | MIT

### CODE REVIEW

**Comment by trsteel88** [comment]
@robfrawley I've updated the travis config to test against 0.6 and 0.7.

It looks like something has failed that isn't failed to the 0.7 change? Are you able to re-execute the tests on your end?

**Comment by trsteel88** [comment]
@robfrawley any idea why that 1 test is failing. That wouldn't be from this PR's changes.

https://travis-ci.org/liip/LiipImagineBundle/jobs/232720653

**Comment by robfrawley** [comment]
I'll take a closer look at this late tonight.

**Comment by trsteel88** [comment]
Thank you.

**Comment by robfrawley** [comment]
@trsteel88 Are you aware of any changes to the grayscale handling with the new Imagine library version?

**Comment by trsteel88** [comment]
@robfrawley no I'm not. However, that failed test is on the older version anyway?

It looks like it's only the php5.3 test failing running ~0.6

**Comment by trsteel88** [comment]
@robfrawley no I'm not. However, that failed test is on the older version anyway?

It looks like it's only the php5.3 test failing running ~0.6

**Comment by robfrawley** [comment]
I re-executed it; let's see how that goes. Otherwise I'll but this PR and perform some local tests to determine what's going on.

**Comment by trsteel88** [comment]
Any luck with your local tests @robfrawley?

**Comment by trsteel88** [comment]
Hey @robfrawley, how can I help to get this progressed?

**Comment by robfrawley** [comment]
We need to fix the merge conflicts and resolve the build failures, the latter of which I don't have too much time to figure out ATM.

**Comment by robfrawley** [comment]
If you can make everything green I'd be happy to include it in the `1.8.1` release, which is likely to hit the streets around 2017-07-01.

**Comment by robfrawley** [comment]
@trsteel88 Thanks for your PR; an alternate solution to resolve the issue mentioned in this PR has been opened as #958.

**Pull request closed without merging**
