### PR TITLE
[Cache Resolver] Implement relative web path resolver

### PR DESCRIPTION
**Pull request by nmuntyanov**
#| Q | A
| --- | ---
| Branch? | 2.0 
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | https://github.com/liip/LiipImagineBundle/issues/1050
| License | MIT

Added new path resolver for relative paths creation 
(RelativeWebPathResolver && RelativeWebPathResolverFactory) 

usage example: 
```php
liip_imagine:
  resolvers:
     default:
       relative_web_path:
         web_root:  "%kernel.root_dir%/../web"
         cache_prefix: assets
```

### CODE REVIEW

**Comment by makasim** [comment]
It would better to register a new resolver for that, instead of adding a bool flag.

**Comment by robfrawley** [comment]
Once we work out all the code implementation details (which I'll provide my comments on tomorrow once I get a chance to review everything), be advised that we only accept PRs that includes documentation. You should add the appropriate files in the `Resources/doc` directory and you can build the RST files to HTML by following the [Wiki article](https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation).

**Comment by maximgubar** [comment]
@nmuntyanov please resolve conflicts on this PR, so it could be processed further.

**Comment by nmuntyanov** [comment]
Resolved

**Comment by nmuntyanov** [comment]
Tests were fixed here: https://github.com/liip/LiipImagineBundle/pull/1087

**Comment by nmuntyanov** [comment]
@robfrawley check this PR please.

**Comment by maximgubar** [comment]
since default branch was changed to `master`, please update the base branch for this PR

**Comment by nmuntyanov** [comment]
@maximgubar updated

**Comment by icedevelopment** [comment]
Any news regarding this PR? @maximgubar @nmuntyanov 
Would be really nice to have this feature.

**Comment by Nuboskill** [comment]
Any news?

**Comment by michellesanver** [comment]
Replaced by https://github.com/liip/LiipImagineBundle/pull/1233

**Pull request closed without merging**
