### PR TITLE
composer: allow Symfony 5

### PR DESCRIPTION
**Pull request by TomasVotruba**
We wanted to ugprade to Symfony 5 released yesterday, but this bundle is blocking us :/

### CODE REVIEW

**Comment by michellesanver** [comment]
Hi, thanks a lot for your contribution Tomas! :)

**Comment by TomasVotruba** [comment]
Hey Michelle :rainbow: :unicorn:  

Long time no see, have a beautiful night :star2:

**Comment by dbu** [comment]
erm, the build is failing: `PHP Fatal error:  Uncaught Error: Class 'Symfony\Bundle\FrameworkBundle\Tests\TestCase' not found in /home/travis/build/liip/LiipImagineBundle/Tests/Exception/Imagine/Filter/PostProcessor/InvalidOptionExceptionTest.php:20`

i fear there is some change with symfony 5 that needs some hackery to support both 4 and 5. i did some nice horrible things for https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/533 which might serve as inspiration.

i'd recommend to add a flex build that forces symfony 5 - currently it seems like some components got installed with version 4, likely because version constraints in dependencies.

it is problematic if composer.json allows to install with symfony 5 when it might not actually works.

**Comment by michellesanver** [comment]
Oh shit, somehow missed that, got too used to gitlab 😐 I’ll revert this when I’m back at my computer in about an hour.

**Comment by michellesanver** [comment]
Ok reverted I’ll look after dinner how to get this to run on SF 5.

**Comment by dbu** [comment]
thanks. i might be able to help a bit tomorrow. if needed, ping me.

**Comment by michellesanver** [comment]
Scratch the after dinner part. I’ll look tomorrow during work hours. My son needs me more than imagine does. If it’s urgent for anyone in the meanwhile feel free to fix it and ping me for a review.

**Comment by michellesanver** [comment]
Actually, as the original contributor is this something you would be willing to contribute @TomasVotruba and yeah, long time no see! 💚🦄 🌈

**Comment by TomasVotruba** [comment]
I don't have time now, preparing first public Symfony training tomorrow

**Comment by michellesanver** [comment]
No worries! I’ll look tomorrow, and good luck with your training 😁👍🏻

**Pull request merged**
