### PR TITLE
Add support for the new quality options

### PR DESCRIPTION
**Pull request by patrickli**
This adds support for the following new quality options:

 * jpeg_quality
 * png_compression_level
 * png_compression_filter

### CODE REVIEW

**Comment by lsmith77** [comment]
needs a rebase .. also tests would be good.

**Comment by makasim** [comment]
We really need this feature but I am not sure about the implementation.

**Comment by patrickli** [comment]
Rebased. However I am not sure if unit test is any helpful since these options are just passed own to imagine.

**Comment by makasim** [comment]
hm, the PR looks unfinished. there is not any tests and you just defined properties but do not use them anywhere

**Comment by lsmith77** [comment]
@makasim this PR just adds options for Imagine, so they are passed along with the other options.

@patrickli in terms of tests you just need to ensure that they are properly set https://github.com/liip/LiipImagineBundle/tree/master/Tests/DependencyInjection

**Comment by makasim** [comment]
@lsmith77 thanks for the explanation

**Comment by patrickli** [comment]
Unit test added.

**Comment by makasim** [comment]
@patrickli thanks

**Pull request merged**
