### PR TITLE
Fix special characters encoding in URL path

### PR DESCRIPTION
**Pull request by torinaki**
| Q | A
| --- | ---
| Branch? | 2.0
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | #1143
| License | MIT
| Doc PR | -

### CODE REVIEW

**Comment by torinaki** [comment]
@dbu I had the same question and found the following line in `ImageController`
https://github.com/liip/LiipImagineBundle/blob/4c321e023e06e5541d0312eeea5fbc33e758fea8/Controller/ImagineController.php#L72
So the answer is yes. It is enough to use `urlencode` because `\` isn't encoded.

I can create another method just for consistency and use it in `ImageController`

**Comment by dbu** [comment]
that would be great, then its more explicit that these operations are related.

**Comment by dbu** [comment]
and can you please rebase on master? we fixed the build there...

**Comment by torinaki** [comment]
@dbu I have made changes. Please review the latest changes in PR

**Pull request merged**
