### PR TITLE
Merge 2.0 branch into master

### PR DESCRIPTION
**Pull request by franmomu**
| Q | A
| --- | ---
| Branch? | master
| Bug fix? | yes
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | 
| License | MIT
| Doc PR | 

This is like https://github.com/liip/LiipImagineBundle/pull/1199, merging 2.0 branch into master so lost commits are recovered in `master` as well

### CODE REVIEW

**Comment by dbu** [comment]
i am confused by the branches in this repository. master currently only has the alias that 1.0-dev is version 1, but has no alias for what the master branch should see. if master is 2.x, we should not have a 2.0 branch. if master is 1.x we should not have had the 1.0 branch and should rather merge 1.0 to master than merge 2.0 to master.

note that there is no release of version 2 yet, so master can't mean 3.x. @lsmith77 or @michellesanver can one of you help us out here and clarify this?

**Comment by lsmith77** [comment]
@maximgubar might remember the details .. but afaik 2.0 was used to prepare the 2.0 release .. after the 2.0 release, master became the source for 2.0 releases .. but I am not 100% sure

**Comment by dbu** [comment]
oh, i overlooked the 2.0.0 and 2.1.0 releases because older tags use the `v` prefix. does 2.0 to master have other differences than what you added from 1.0 @franmomu ? if master has no BC breaks versus 2, i suggest we merge this and then remove the 2.0 branch to avoid confusion.

and imho there should be a branch alias for `dev-master: 2.x` if master represents version 2.

**Comment by franmomu** [comment]
oops I thought 2.0 branch was for 2.x releases. Apart from the changes from 1.0, here are included a couple of commits (https://github.com/liip/LiipImagineBundle/commit/644059056f65be78997f6105288db35793fe23fe and https://github.com/liip/LiipImagineBundle/commit/647d51e0952a342a202deaa076b8f17ece44402e) that are in 2.0 and not in master

**Comment by dbu** [comment]
looking at https://github.com/liip/LiipImagineBundle/compare/2.0...master there seem to be cs cleanups and one big new feature, the configuration model classes. i don't think they are a BC break, so imho we can merge this and then remove the 2.0 branch for clarity. wdyt @michellesanver ?

**Comment by michellesanver** [comment]
Sounds like a perfect plan! :)

**Pull request merged**
