### PR TITLE
Upgrade 2.0 from 1.0

### PR DESCRIPTION
**Pull request by dbu**
| Q | A
| --- | ---
| Branch? | 2.0
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | see travis
| Fixed tickets | -
| License | MIT
| Doc PR | -

it seems that 2.0 has been way behind 1.0. i solved a lot of conflicts, there might be issues with some of the resolutions. we also have a couple of deprecated things now that should be removed in the 2.0 branch. but i think that should be done in a separate pull request.

### CODE REVIEW

**Comment by lsmith77** [comment]
there are also now a few more commits that need to be merged ..

**Comment by lsmith77** [comment]
@robfrawley can you take this one on?

**Comment by robfrawley** [comment]
I'll try to rebase this properly over the current 2.x commit and then take a look and see if everything looks okay. Likely by the end of the week...

**Comment by pyrech** [comment]
Sorry to bother you but is there an ETA for 2.0?
Because at the moment, there is still no release compatible with Symfony 4.0 :confused:

**Comment by robfrawley** [comment]
You can reference our [milestones page](https://github.com/liip/LiipImagineBundle/milestone/6) for `2.0` release information, as well as the open issues posing the same question: #1052, #1064. This project has few active maintainers; those of us contributing provide as much of our free time to this project as we can. The `2.0` release is coming shortly.

**Comment by pyrech** [comment]
Sorry that I did not look at milestones page, nor the opened issues :disappointed:. Anyway thanks for your answer, I didn't mean to put any pressure on the maintainers. I will try to see if I can help on some issues when I come back from holidays.

**Comment by robfrawley** [comment]
@pyrech It's all good. We'll have the release out the door either this coming Monday or the following one.

**Comment by maximgubar** [comment]
@dbu, @lsmith77, @robfrawley what is blocking this PR to be merged (except failed tests and conflicts) ?

**Comment by tifabien** [comment]
It seems you released the 2.0.0 without having this PR merged. Is it normal ? This makes the upgrade almost impossible.
Is there anything we can do?

**Comment by dbu** [comment]
i don't think this should be rebased - that will lose the git commit ids, and then you can't ever merge the 1.0 branch into 2.0 again when there is a bugfix to the legacy branch.

and yes, this should be merged asap and a 2.0.1 or maybe 2.1.0 be released.

**Comment by lsmith77** [comment]
@maximgubar can you have a look?

**Comment by maximgubar** [comment]
@robfrawley, @makasim, @cedricziel, @imanalopher, @antoligy, @rpkamp, @lstrojny, @cmodijk, @dbu 

Since this PR was not merged in time and due to its current complexity we propose to split it in small PRs. So basically each author takes his changes and creates a new PR against `2.0` branch.

**Comment by robfrawley** [comment]
@maximgubar: That sounds like a solid plan. Once we get the major items merged separately, we can tag a 2.1.0 release and improve backward compatibility.

There are commits and lines of code in this PR that were intended only for the `1.x` branch (for example deprecation notices) and I don't think anyone is familiar enough with everyone else's commits to reliably merge this together without guidance. Relying on the original authors to submit PRs to `2.x` branch is a reasonable way to manage this and will help ensure code we **don't** want in `2.x` doesn't accidentally end up there.

I'll get my changes together this week.

**Comment by cmodijk** [comment]
My pull request is in the 1.0 branch do you want me to create a new pull for the 2.0 branch?
* https://github.com/liip/LiipImagineBundle/blob/1.0/Resources/doc/filters/general.rst
* https://github.com/liip/LiipImagineBundle/blob/2.0/Resources/doc/filters/general.rst

**Comment by robfrawley** [comment]
@cmodijk Give it a few days (unless you want to creater the PR yourself); many of the changes are extremely minor (such as your PR to add "centerright" and "centerleft" positioning to the background filter loader) and I think I can automate such cases without each individual author's manual handling.

@maximgubar This week I happen to have tons of free time and an employer sympathetic to open source software, so I'll handle the vast majority of the updates to `2.0` from `1.0` (using separate PRs as appropriate), and then next weekend I'll tag all users that don't have a straightforward PR from `1.0` and request that they manually re-submit the changes against `2.0`. We can give them an additional week, and then plan to tag `2.1.0` on Monday, June 4th (two weeks from today). How does that sound?

**Comment by tifabien** [comment]
@robfrawley my comment was bad. I meant that when I saw the 2.0 release I tried to upgrade but was surprise to see that some 1.0 feature was not there or removed (that's why I added a missing note in the upgrade guide ;)). I'm thankful for all the great job your are doing for maintaining this bundle! 
I think I'm too accustomed with the smooth SF upgrade process :)

**Comment by robfrawley** [comment]
I've created a project to manage this process here: https://github.com/liip/LiipImagineBundle/projects/2. I will be updating that with all the required entries later today, and progress can be tracked there. @maximgubar Got the first one for you to review #1096 (glad to have someone who can regularly review things now; there was a period of time where I was reviewing my own contributions, a practice I do not particularly like). :-)

**Comment by maximgubar** [comment]
since default branch was changed to `master`, please update the base branch for this PR

**Comment by dbu** [comment]
done in #1199

**Pull request closed without merging**
