### PR TITLE
Fix background filter

### PR DESCRIPTION
**Pull request by jockri**
This solves #640

### CODE REVIEW

**Comment by makasim** [comment]
Does it work for you?

**Comment by jockri** [comment]
Yes, before this change I was receiving this error: 
`Error: Attempted to call method "palette" on class "Imagine\Imagick\Image" in vendor/liip/imagine-bundle/Liip/ImagineBundle/Imagine/Filter/Loader/BackgroundFilterLoader.php at line 22`
And now it works again.

**Comment by makasim** [comment]
What is the version of imagine library you have?

**Comment by jockri** [comment]
```
        "name": "imagine/imagine",
            "version": "v0.5.0",
            "source": {
                "type": "git",
                "url": "https://github.com/avalanche123/Imagine.git",
                "reference": "f64ec666baaa800edcbf237db41121a569230709"
            },
```

**Pull request merged**
