### PR TITLE
[Filter] Add "fixed-size" filter implementation

### PR DESCRIPTION
**Pull request by peter-gribanov**
| Q | A
| --- | ---
| Branch? | 1.0
| Bug fix? | yes
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | #560
| License | MIT
| Doc PR | -

At the moment there is no way to create a fixed-size image.
This is a new filter that does this.

See https://github.com/liip/LiipImagineBundle/issues/560#issuecomment-275694967 for more details.

Usage
-------

```yml
liip_imagine:
    filter_sets:
        my_thumb:
            filters:
                fixed: { width: 120, height: 90 }
```

### CODE REVIEW

**Comment by lsmith77** [comment]
@antoligy / @robfrawley how do we want to deal with this .. 1.0 or 2.0 ?

**Comment by robfrawley** [comment]
My opinion is to have this as a new feature for our new 2.x major release. (Tagging as such now, but we can change back to 1.0 if others disagree)

**Comment by robfrawley** [comment]
@peter-gribanov Please update/add to the RST documentation to include information about the new filter implementation you are introducing here. Reference the recent PR #941, which adds a resolution filter, for information on the expected additions and updates that need to be included in this PR.

*Note: While working on the RST docs, please be sure to test your changes and view the rendered output for correctness in a web browser of your choice. See the wiki entry for [building the RST documentation](https://github.com/liip/LiipImagineBundle/wiki/Building-RST-Documentation) for an overview of how to compile the RST files into HTML.*

Otherwise, everything else looks great! Thanks for the contribution.

**Comment by peter-gribanov** [comment]
@robfrawley I added documentation about the filter. Maybe you want to add something.

**Comment by robbeman** [comment]
@robfrawley Thanks for the mention ❤️. (Yes, I'm that slow in noticing these things, hehe.)

**Comment by crabnky** [comment]
Any idea when this can be merged?

**Comment by peter-gribanov** [comment]
@maximgubar thanks 👍

**Comment by florianajir** [comment]
This filter is not available in v2, can anyone told me how to get the same behavior from built in filters ? I tried thumbnail with allow_upscale but this is not the same behavior with upscale

**Pull request merged**
