### PR TITLE
Fix RST indentation error in AWS S3 cache resolver documentation

### PR DESCRIPTION
**Pull request by GeoffreyHervet**

### CODE REVIEW

**Comment by robfrawley** [comment]
@GeoffreyHervet I don't follow what you're trying to fix... you added an extra tab? Can you provide some clarity. Thanks!

**Comment by GeoffreyHervet** [comment]
On the [Symfony documentation](http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/aws_s3.html) the code yml section is broken :( It should fix it. It's also broken with on [github](https://github.com/liip/LiipImagineBundle/blob/1.0/Resources/doc/cache-resolver/aws_s3.rst).

Let me know if I'm wrong,
([my preview with extra tabs](https://github.com/GeoffreyHervet/LiipImagineBundle/blob/fcad56ad60ba96ffa1bf6449a7ec2d4f18558dbf/Resources/doc/cache-resolver/aws_s3.rst))

Best,
G

**Comment by robfrawley** [comment]
@GeoffreyHervet I've added a wiki article on building the RST documentation, which should assist those such as yourself testing changes/fixes to the documentation moving forward.

Thanks for this PR!

**Comment by robfrawley** [comment]
@lsmith77 Ping (RST documentation rebuild need to be triggered)

**Comment by GeoffreyHervet** [comment]
@robfrawley Thank the link & the merge :)

**Comment by lsmith77** [comment]
@javiereguiluz is this done automatically at regular time intervals or is this a manual process?

**Comment by javiereguiluz** [comment]
@lsmith77 it's automatic. The published page seems to have applied the changes of this PR: http://symfony.com/doc/current/bundles/LiipImagineBundle/cache-resolver/aws_s3.html

However, this PR may have used too much indentation for the last level (`key`, `secret`, etc.)

indentation

**Comment by robfrawley** [comment]
@javiereguiluz Thanks for the info; we weren't sure if it was automatically handled. Appreciate it!

**Pull request merged**
