### PR TITLE
Fix strange wording in readme

### PR DESCRIPTION
**Pull request by svenluijten**
To do something "pragmatically" is to do it from a practical point of view. I'd say this entire bundle is made to solve uploading "pragmatically". I think the word you were looking for in this section was "programmatically".

### CODE REVIEW

**Comment by cedricziel** [comment]
Good catch, thank you!

**Comment by antoligy** [comment]
Thanks for the contribution!  Merged and cherry-picked into 2.0.

**Comment by svenluijten** [comment]
👌 Sweet!

**Comment by robfrawley** [comment]
Good find!

**Pull request merged**
