### PR TITLE
Release 1.9.0

### PR DESCRIPTION
**Pull request by robfrawley**
| Q | A
| --- | ---
| Branch? | 1.0
| Bug fix? | yes
| New feature? | yes
| BC breaks? | no
| Deprecations? | yes
| Tests pass? | yes
| Fixed tickets | 
| License | MIT
| Doc PR | 

Update the [`CHANGELOG.md`](https://github.com/robfrawley/LiipImagineBundle/blob/f0d636dc6fe95914bb10849d1a1739eb39e5707b/CHANGELOG.md) and [`UPGRADE.md`](https://github.com/robfrawley/LiipImagineBundle/blob/f0d636dc6fe95914bb10849d1a1739eb39e5707b/UPGRADE.md) files for the `1.9.0` release.

### CODE REVIEW

**Comment by robfrawley** [comment]
It would be much appreciated if either @antoligy or @cedricziel can take a moment to review the release changes so that I can get the `1.9.0` release officially tagged. There have been a bunch of recent requests for the new tag, so I took the time to merge all the outstanding `1.9.0`-labeled PRs and fix some issues introduced. I think we're ready to go!

**Comment by robfrawley** [comment]
@antoligy @cedricziel Can I get a quick review so we can tag the `1.9.0` release? You just need to review the first commit in this PR (https://github.com/liip/LiipImagineBundle/pull/983/commits/a3bde59e1de60b6bd7ce0ed5f9ccca1da1d7d7ef); the second one is just formatting changes (hence its size).

**Comment by antoligy** [comment]
Sorry for the delay, have been super rammed! Thanks for preparing this, I'll check it out later on today!

**Comment by robfrawley** [comment]
No worries; I can absolutely understand being swamped and not having time to allocate to every open source project! ;-) Thanks for setting aside some time. :1st_place_medal:

**Comment by cedricziel** [comment]
Thx for the preparation!

**Comment by robfrawley** [comment]
@cedricziel Thanks for handling and merging a few PRs over the last few weeks; I didn't have **any** time to contribute to this project over the last month and I know a few people were becomming irritated in their PRs not being merged, so I'm glad you handled some. Between us three we're keeping this project moving forward pretty well, IMHO.

**Comment by cedricziel** [comment]
Thx to you guys as well - IMHO it's hard to always be on spot for open source and I'm glad there's the 3 of us :)

**Comment by robfrawley** [comment]
Unless anyone adds any additional comments, I'll merge this and tag the new release tomorrow sometime during the day.

**Pull request merged**
