### PR TITLE
Destruct image to cleanup memory

### PR DESCRIPTION
**Pull request by cmodijk**
In #633 we where encountered a lot of memory leak using the imagick extension. Imagick and Imagine fix that by using the `__destruct` method but because we use this in a long running process the `__destruct` is never getting called.  This pull requests fixes that issues.

### CODE REVIEW

**Comment by makasim** [comment]
I dont like it, kind of hack. We can add an event dispatch there, like POST_FILTER or so and you can add a listener with custom logic in your app.

**Comment by cmodijk** [comment]
@makasim I don't like it to but it don't know if an event is going to help because  in the event you don't know of the imagick object is different than the previous one. And if you `__destruct ` the images that is still being used you get other problems and errors from that.

**Comment by makasim** [comment]
Okay, can you add a comment there (with a link to the issue) cuz it is not obvious from the code what it solves.

**Comment by makasim** [comment]
@cmodijk ping

**Comment by cmodijk** [comment]
@makasim Sorry! To what issue do you want to point the link? This pull request or the original problem?

**Comment by cmodijk** [comment]
@makasim I added a comment but I'm not so good with words in English could you please check the comments?

**Comment by mattjanssen** [comment]
Thank you! I spent hours yesterday debugging this typical-PHP memory leak. I was about to submit a PR, but I see you took care of it. :+1:

I also used the __destruct() method, even though it feels gross; I could think of no better way. The comments are valuable.

**Pull request merged**
