### PR TITLE
Fix event dispatcher deprecation sf 4.3

### PR DESCRIPTION
**Pull request by franmomu**
| Q | A
| --- | ---
| Branch? | 2.0
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | 
| License | MIT
| Doc PR | 

An attempt to get rid of event dispatcher deprecations using symfony 4.3. If someone can think of other way... I'm happy to change it :)

### CODE REVIEW

**Comment by dbu** [comment]
thanks for this one!

in #1185, someone mentioned a legacy event dispatch proxy. maybe you could use that?

**Comment by franmomu** [comment]
yeah it was me 😆, after taking a look at that class I find it a little bit tricky, because, if we do this in the constructor (we can only use `LegacyEventDispatcherProxy` in sf >= 4.3):

```php
if (class_exists(LegacyEventDispatcherProxy::class)) {
    $this->dispatcher = LegacyEventDispatcherProxy::decorate($dispatcher);
} else {
    $this->dispatcher = $dispatcher;
}
```
we have to keep dispatching events like this (because with sf <4.3 it won't work):
```php
$this->dispatcher->dispatch(ImagineEvents::PRE_RESOLVE, $preEvent);
```
So the `LegacyEventDispacherProxy` executes this:
```php
@trigger_error(sprintf('The signature of the "%s::dispatch()" method should be updated to "dispatch($event, string $eventName = null)", not doing so is deprecated since Symfony 4.3.', $r->class), E_USER_DEPRECATED);
```
That's why I decided not to use it.

**Comment by fbourigault** [comment]
I'm not super fan of using the Kernel version to detect with signature to use.

Someone may be stuck with http-kernel 4.2 and using event-dispatcher 4.3 and this would fail.

This is an edge case, but not impossible.

As since 4.3 the event-dispatcher implements `Symfony\Contracts\EventDispatcher\EventDispatcherInterface`, what about checking if the dispatcher implements this interface or not to choose the right signature?

**Comment by dbu** [comment]
thank you!

**Comment by franmomu** [comment]
you're very welcome!

**Pull request merged**
