### PR TITLE
Update WebPathResolver.php

### PR DESCRIPTION
**Pull request by gonzalovilaseca**
Missing empty line

### CODE REVIEW

**Comment by makasim** [comment]
StylieCI does not like the change: https://styleci.io/analyses/8QbPgX

**Comment by gonzalovilaseca** [comment]
Something is wrong with StyleCI then.

**Comment by makasim** [comment]
I cannot merge it then

**Comment by javiereguiluz** [comment]
@gonzalovilaseca the problem is that your new line is not empty but it contains three white spaces. If you remove those white spaces, everything should be fine.

**Pull request closed without merging**
