### PR TITLE
Updating twig call to utilise asset(), to match README.md (closes #830)

### LINKED ISSUE #830: Update RST documentation to use `asset()` Twig function
The `README.md` code examples now make use of the Twig `asset()` function, per #825. We should bring the relevant examples in the RST documentation in-line with this convention. While the prior mentioned PR affected only four `README.md` lines, I know that their are a few additional examples in the RST documentation, all of which should be consistent, IMHO.

### PR DESCRIPTION
**Pull request by antoligy**
See #834, only on my fork and with without me breaking the test suite.

### CODE REVIEW

**Comment by robfrawley** [comment]
Hmm... why is Travis trying to clone branch `feature/use-asset-for-twig`?

**Comment by antoligy** [comment]
Not sure, I reckon it's cached a copy of the repo with my initial incorrect branch and it's trying to somehow resolve that commit to that branch - All the more reason to avoid pushing to branches on here!

**Comment by robfrawley** [comment]
@antoligy Cherry picked your commit for 2.x branch: https://github.com/liip/LiipImagineBundle/commits/2.0

**Comment by antoligy** [comment]
Sounds good-  Is it worth establishing a standard for how we push 1.0 changes to 2.0?  I am happy to cherry pick but obviously this becomes more of a problem with more commits.

**Pull request merged**
