### PR TITLE
Add configuration options for jpegoptim post-processor

### PR DESCRIPTION
**Pull request by dylanschoenmakers**
Added configuration options (max, progressive) for the jpegoptim post-processor:
```
filter_sets:
        my_filter:
            post_processors:
                jpegoptim: { max: 65, progressive: false }
```

### CODE REVIEW

**Comment by lsmith77** [comment]
can you add a note to the docs and rebase on master?

**Comment by lsmith77** [comment]
BTW this PR seems to overlap with #720

**Comment by antoligy** [comment]
Might make sense to delay this until after #720 is merged, then it can be rebased and the constructor conflicts can be resolved

**Comment by dylanschoenmakers** [comment]
Any chance this could be merged now with my latest changes? I've copied the constructor arguments from #720 to match.

**Comment by lsmith77** [comment]
so you think this PR now makes #720 obsolete?

**Comment by antoligy** [comment]
I feel like the two are halves reaching towards the same goal, but with slightly different features and ultimately we should be okay to merge either in first.

If _this_ is merged in first, then I'm happy to rebase #759 again against this today and resolve the constructor conflicts, which will then allow for that to be closed too.

**Comment by lsmith77** [comment]
ok .. lets go!

**Comment by antoligy** [comment]
wooo!

**Pull request merged**
