### PR TITLE
Modify some PHP Annotations

### PR DESCRIPTION
**Pull request by imanalopher**
| Q | A
| --- | ---
| Branch? | 1.0 
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | n/a
| License | MIT
| Doc PR |

### CODE REVIEW

**Comment by robfrawley** [comment]
Please complete the PR issue template.

**Comment by imanalopher** [comment]
@robfrawley, what do you mean? I don't understand you.

**Comment by robfrawley** [comment]
When you create a PR, the following template exists in the message body:

```
| Q | A
| --- | ---
| Branch? | 1.0 or 2.0 <!--choose version number-->
| Bug fix? | yes/no
| New feature? | yes/no
| BC breaks? | yes/no
| Deprecations? | yes/no
| Tests pass? | yes/no
| Fixed tickets | <!-- #-pre-fixed issue number(s), if any -->
| License | MIT
| Doc PR | <!--highly recommended for new features-->
```

This should be properly edited to describe the different attributes pertinent to this PR, for example:

```
| Q | A
| --- | ---
| Branch? | 1.0
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | n/a
| License | MIT
| Doc PR | n/a
```

Which would render as the following in the opening comment for this PR:

| Q | A
| --- | ---
| Branch? | 1.0
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | n/a
| License | MIT
| Doc PR | n/a

**Comment by antoligy** [comment]
@imanalopher -- Firstly, thanks for taking the time to contribute!

Would you mind amending the template so we can review this a bit quicker?  Hate to be a stickler but even with smaller issues it's a convention to ease all our lives.

Thanks again! 🙂

**Comment by cedricziel** [comment]
I fixed the template for you - thx for taking the time!

**Comment by robfrawley** [comment]
@cedricziel This has an open change request, FYI. :-)

**Pull request merged**
