### PR TITLE
[Docs] Correct a tyop in the filters section of RST documentation

### PR DESCRIPTION
**Pull request by broiniac**
| Q | A
| --- | ---
| Branch? | 2.0 
| Bug fix? | no
| New feature? |no
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes
| Fixed tickets | no
| License | MIT
| Doc PR | no

Fix tyop in Filters section

### CODE REVIEW

**Comment by broiniac** [comment]
Typo exists on 1.0 branch as well. Should I made new PR for this? It's just a small typo, really.

**Comment by robfrawley** [comment]
I'm not particularly concerned about the `1.0` documentation as our `2.0` release will be out this week and with most people moving to Symfony `3.4` or above (the requirements for `2.0`) I dought many will still be running `1.0` after this week.

**Comment by robfrawley** [comment]
Thanks @broiniac!

**Comment by broiniac** [comment]
No no, thank YOU for this awesome piece of software!

W dniu 21.03.2018 o 02:43, Rob Frawley 2nd pisze:

**Pull request merged**
