### PR TITLE
Adding optipng post transformer

### PR DESCRIPTION
**Pull request by gouaille**

### CODE REVIEW

**Comment by makasim** [comment]
tests fails, could @gouaille please fix them?

https://travis-ci.org/liip/LiipImagineBundle/jobs/101123613

**Comment by gouaille** [comment]
Edited.

StyleCI seems to be ok if we check the details ?

**Comment by makasim** [comment]
Have you tested it in real world? Does it work for you?

**Comment by gouaille** [comment]
Yes, but my project is private atm and i can't show you an example

**Comment by makasim** [comment]
I do not need an example, just need confirmation that the solution was tested in real world.

**Comment by makasim** [comment]
@gouaille Could you please add some words to the documentation about the new post proceesor

https://github.com/liip/LiipImagineBundle/blob/master/Resources/doc/filters.rst#post-processors

**Comment by gouaille** [comment]
It is working in real world.

Doc updated.

**Comment by makasim** [comment]
Thanks

**Pull request merged**
