### PR TITLE
Exclude "Tests" directory from classmap

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by antoligy** [comment]
I see you've created this PR across a bunch of bundles at once, cheers for that.

More details here if anybody is interested - https://github.com/Sylius/Sylius/pull/7035

I'm okay with this, to me the risk of BC is very low though it might be worth saving this for the next 1.0 minor release versus tagging as a patch.
Definitely good to go in 2.0 IMO.

**Comment by pamil** [comment]
Changed base branch, rerun Travis.

**Comment by robfrawley** [comment]
:+1: for 2.0

**Comment by robfrawley** [comment]
Oops: didn't mean to close.

**Comment by robfrawley** [comment]
Anyone seen any negative impact on this? Otherwise I submit we merge tomorrow.

**Comment by antoligy** [comment]
I'm happy with that!

**Comment by antoligy** [comment]
🎉

**Pull request merged**
